name: hw3-gam
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pyarrow
  - matplotlib
  - scikit-learn
  - jupyter
  - ipykernel
  - pip
  - s3fs
  - fsspec
  - pip:
    - pygam
